spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Bank
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: admin123
    key-store-type: PKCS12
    key-alias: tomcat
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,env,beans,threaddump
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
        step: 1m